import teams

def getTeams():
    bracketTeams = [ 
        #S
        teams.Team('Kansas',1),
        teams.Team('Austin Peay',16),
        teams.Team('Colorado',8),
        teams.Team('Connecticut',9),
        teams.Team('Maryland',5),
        teams.Team('S Dakota St',12, 'South Dakota St'),
        teams.Team('California',4),
        teams.Team('Hawaii',13),
        teams.Team('Arizona',6),
        teams.Team('Wichita St',11),
        teams.Team('Miami',3,'Miami FL'),
        teams.Team('Buffalo',14),
        teams.Team('Iowa',7),
        teams.Team('Temple',10),
        teams.Team('Villanova',2),
        teams.Team('UNC Asheville',15, 'North Carolina Asheville'),
        #W
        teams.Team('Oregon',1),
        teams.Team('Holy Cross',16),
        teams.Team('St Joseph\'s PA',8, 'Saint Josephs'),
        teams.Team('Cincinnati',9),
        teams.Team('Baylor',5),
        teams.Team('Yale',12),
        teams.Team('Duke',4),
        teams.Team('UNC Wilmington',13, 'North Carolina Wilmington'),
        teams.Team('Texas',6),
        teams.Team('Northern Iowa',11),
        teams.Team('Texas A&M',3, 'Texas AM'),
        teams.Team('WI Green Bay', 14, 'Green Bay'),
        teams.Team('Oregon St',7),
        teams.Team('VA Commonwealth',10, 'Virginia Commonwealth'),
        teams.Team('Oklahoma',2),
        teams.Team('CS Bakersfield',15, 'Cal St Bakersfield'),
        #E
        teams.Team('North Carolina',1),
        teams.Team('FL Gulf Coast',16, 'Florida Gulf Coast'),
        teams.Team('USC',8,'Southern California'),
        teams.Team('Providence',9),
        teams.Team('Indiana',5),
        teams.Team('Chattanooga',12),
        teams.Team('Kentucky',4),
        teams.Team('Stony Brook',13),
        teams.Team('Notre Dame',6),
        teams.Team('Michigan',11),
        teams.Team('West Virginia',3),
        teams.Team('SF Austin',14, 'Stephen F Austin'),
        teams.Team('Wisconsin',7),
        teams.Team('Pittsburgh',10),
        teams.Team('Xavier',2),
        teams.Team('Weber St',15),
        #MW
        teams.Team('Virginia',1),
        teams.Team('Hampton',16),
        teams.Team('Texas Tech',8),
        teams.Team('Butler',9),
        teams.Team('Purdue',5),
        teams.Team('Ark Little Rock',12,'Arkansas Little Rock'),
        teams.Team('Iowa St',4),
        teams.Team('Iona',13),
        teams.Team('Seton Hall',6),
        teams.Team('Gonzaga',11),
        teams.Team('Utah',3),
        teams.Team('Fresno St',14),
        teams.Team('Dayton',7),
        teams.Team('Syracuse',10),
        teams.Team('Michigan St',2),
        teams.Team('MTSU',15,'Middle Tennessee'),
        ]
    return bracketTeams